sudo: false
cache:
directories:
- $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27,codecov-py27
    - python: "3.4"
      env: TOXENV=py34,codecov-py34
    - python: "3.5"
      env: TOXENV=py35,codecov-py35
    - python: "3.6"
      env: TOXENV=py36,codecov-py36
    - python: "3.7"
      env: TOXENV=py37,codecov-py37
    - python: "pypy"
      env: TOXENV=pypy,codecov-pypy
    - python: "pypy3"
      env: TOXENV=pypy3,codecov-pypy3
    - python: "2.7"
      env: TOXENV=packaging-py27


install:
  - pip install tox


script:
  - tox
