sudo: false
cache:
directories:
- $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=test-py27,codecov-py27
    - python: "3.4"
      env: TOXENV=test-py34,codecov-py34
    - python: "3.5"
      env: TOXENV=test-py35,codecov-py35
    - python: "3.6"
      env: TOXENV=test-py36,codecov-py36
    - python: "3.7"
      env: TOXENV=test-py37,codecov-py37
    - python: "pypy"
      env: TOXENV=test-pypy,codecov-pypy
    - python: "pypy3"
      env: TOXENV=test-pypy3,codecov-pypy3
    - python: "2.7"
      env: TOXENV=packaging-py27


install:
  - pip install tox


script:
  - tox
